services:
    App\Infrastructure\TodoList\Persistence\TodoListRepository: ~

    App\Domain\Shared\Persistence\EventSourcedRepositoryInterface $todoListEventStore: '@App\Infrastructure\TodoList\Persistence\TodoListRepository'
