services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'

    _instanceof:
        App\Domain\Shared\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus, method: handle }

        App\Domain\Shared\Event\EventHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus, method: handle }

        App\Domain\Shared\Projector\ProjectorInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus, method: handle }

        App\Domain\Shared\Query\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }
